version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: hospital_db
    environment:
      POSTGRES_DB: hospital
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hospital_network

  app:
    image: your_app_image:latest
    container_name: hospital_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/hospital
      SPRING_DATASOURCE_USERNAME: hospital_user
      SPRING_DATASOURCE_PASSWORD: hospital_password
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - hospital_network

networks:
  hospital_network:
    driver: bridge

volumes:
  db_data:
